Repository Knock-Og/BE, pull requests merged in 2023-04, with the labels that each got.

#130 Refactor : Admin domain Method convention 적용 (#129)
  src/main/java/com/project/comgle/admin/controller/AdminController.java
  src/main/java/com/project/comgle/admin/service/AdminService.java
  src/main/java/com/project/comgle/auth/controller/SmsController.java
  src/main/java/com/project/comgle/auth/service/SmsService.java
Labels: Refactor

#138 Feat : 로그2차(최종)구현
  .github/workflows/gradle.yml
  src/main/java/com/project/comgle/post/controller/LogController.java
  src/main/java/com/project/comgle/post/dto/LogResponseDto.java
  src/main/java/com/project/comgle/post/entity/Log.java
  src/main/java/com/project/comgle/post/service/PostService.java
Labels: Feat

#134 Feat : 페이징 (#104)
  .github/workflows/gradle.yml
  src/main/java/com/project/comgle/bookmark/controller/BookMarkController.java
  src/main/java/com/project/comgle/bookmark/dto/PostPageResponseDto.java
  src/main/java/com/project/comgle/bookmark/repository/BookMarkRepository.java
  src/main/java/com/project/comgle/bookmark/service/BookMarkService.java
  src/main/java/com/project/comgle/mypage/controller/MyPageController.java
  src/main/java/com/project/comgle/mypage/service/MyPageService.java
  src/main/java/com/project/comgle/post/controller/SearchController.java
  src/main/java/com/project/comgle/post/dto/SearchPageResponseDto.java
  src/main/java/com/project/comgle/post/repository/PostRepository.java
  src/main/java/com/project/comgle/post/service/SearchService.java
Labels: Feat

#135 Refactor : Post 관련 부분 리펙토링 #133
  src/main/java/com/project/comgle/post/controller/PostController.java
  src/main/java/com/project/comgle/post/controller/SearchController.java
  src/main/java/com/project/comgle/post/entity/Post.java
  src/main/java/com/project/comgle/post/service/PostService.java
Labels: Refactor

#139 BookMark 관련 부분 리펙토링 Refactor (#136)
  src/main/java/com/project/comgle/bookmark/controller/BookMarkController.java
  src/main/java/com/project/comgle/bookmark/repository/BookMarkFolderRepository.java
  src/main/java/com/project/comgle/bookmark/service/BookMarkService.java
Labels: Refactor

#141 Refactor : 로그2차구현 changedLineNum (#140)
  src/main/java/com/project/comgle/post/service/PostService.java
Labels: Refactor

#144 Fear : AOP를 활용하여 조회 관련 기능 수행 시간 측정 (#143)
  src/main/java/com/project/comgle/admin/controller/CategoryController.java
  src/main/java/com/project/comgle/admin/service/CategoryService.java
  src/main/java/com/project/comgle/bookmark/controller/BookMarkController.java
  src/main/java/com/project/comgle/comment/controller/CommentController.java
  src/main/java/com/project/comgle/global/aop/ExeTimer.java
  src/main/java/com/project/comgle/global/aop/ExecutionTimer.java
  src/main/java/com/project/comgle/member/controller/MemberController.java
  src/main/java/com/project/comgle/mypage/controller/MyPageController.java
  src/main/java/com/project/comgle/post/controller/LogController.java
  src/main/java/com/project/comgle/post/controller/PostController.java
  src/main/java/com/project/comgle/post/controller/SearchController.java
Labels: Feat

#148 Feat : 회원 삭제 기능 구현 (#146)
  src/main/java/com/project/comgle/admin/controller/AdminController.java
  src/main/java/com/project/comgle/admin/service/AdminService.java
  src/main/java/com/project/comgle/bookmark/entity/BookMarkFolder.java
  src/main/java/com/project/comgle/bookmark/repository/BookMarkFolderRepository.java
  src/main/java/com/project/comgle/bookmark/repository/BookMarkRepository.java
  src/main/java/com/project/comgle/global/exception/ExceptionEnum.java
  src/main/java/com/project/comgle/member/entity/Member.java
  src/main/java/com/project/comgle/member/repository/MemberRepository.java
  src/main/java/com/project/comgle/post/entity/Post.java
  src/main/java/com/project/comgle/post/repository/LogRepository.java
  src/main/java/com/project/comgle/post/repository/PostRepository.java
Labels: Feat

#149 Feat : 연락처 중복 확인 여부 (#147)
  src/main/java/com/project/comgle/admin/controller/AdminController.java
  src/main/java/com/project/comgle/admin/service/AdminService.java
  src/main/java/com/project/comgle/global/exception/ExceptionEnum.java
Labels: Feat

#150 Feat : Query DSL 적용 (검색 성능 개선) #145
  src/main/java/com/project/comgle/bookmark/service/BookMarkService.java
  src/main/java/com/project/comgle/post/repository/KeywordRepository.java
  src/main/java/com/project/comgle/post/repository/KeywordRepositoryImpl.java
  src/main/java/com/project/comgle/post/repository/PostRepository.java
  src/main/java/com/project/comgle/post/repository/PostRepositoryImpl.java
  src/main/java/com/project/comgle/post/service/PostService.java
  src/main/java/com/project/comgle/post/service/SearchService.java
Labels: Feat

#155 Feat : 비밀번호 변경 기능 (#152)
  src/main/java/com/project/comgle/global/exception/ExceptionEnum.java
  src/main/java/com/project/comgle/member/controller/MemberController.java
  src/main/java/com/project/comgle/member/dto/LoginRequestDto.java
  src/main/java/com/project/comgle/member/dto/PasswordRequestDto.java
  src/main/java/com/project/comgle/member/service/MemberService.java
Labels: Feat, Refactor

#158 Feat : 검색 결과 필터 기능
  build.gradle
  src/main/java/com/project/comgle/post/controller/SearchController.java
  src/main/java/com/project/comgle/post/repository/PostRepository.java
  src/main/java/com/project/comgle/post/repository/PostRepositoryImpl.java
  src/main/java/com/project/comgle/post/service/SearchService.java
Labels: Feat, Refactor

#159 Fix : Member, Post, Company 상태 Column 추가로 인한 관련 기능 코드 수정 (#153)
  src/main/java/com/project/comgle/admin/controller/AdminController.java
  src/main/java/com/project/comgle/admin/controller/CategoryController.java
  src/main/java/com/project/comgle/admin/service/AdminService.java
  src/main/java/com/project/comgle/admin/service/CategoryService.java
  src/main/java/com/project/comgle/auth/controller/EmailController.java
  src/main/java/com/project/comgle/auth/service/EmailService.java
  src/main/java/com/project/comgle/bookmark/service/BookMarkService.java
  src/main/java/com/project/comgle/comment/controller/CommentController.java
  src/main/java/com/project/comgle/comment/service/CommentService.java
  src/main/java/com/project/comgle/company/controller/CompanyController.java
  src/main/java/com/project/comgle/company/entity/Company.java
  src/main/java/com/project/comgle/company/repository/CompanyRepository.java
  src/main/java/com/project/comgle/company/service/CompanyService.java
  src/main/java/com/project/comgle/global/exception/ExceptionEnum.java
  src/main/java/com/project/comgle/global/security/UserDetailsImpl.java
  src/main/java/com/project/comgle/global/security/UserDetailsServiceImpl.java
  src/main/java/com/project/comgle/global/utils/JwtUtil.java
  src/main/java/com/project/comgle/member/controller/MemberController.java
  src/main/java/com/project/comgle/member/entity/Member.java
  src/main/java/com/project/comgle/member/repository/MemberRepository.java
  src/main/java/com/project/comgle/member/service/MemberService.java
  src/main/java/com/project/comgle/mypage/controller/MyPageController.java
  src/main/java/com/project/comgle/mypage/service/MyPageService.java
  src/main/java/com/project/comgle/post/controller/LogController.java
  src/main/java/com/project/comgle/post/controller/PostController.java
  src/main/java/com/project/comgle/post/entity/Log.java
  src/main/java/com/project/comgle/post/entity/Post.java
  src/main/java/com/project/comgle/post/repository/PostRepository.java
  src/main/java/com/project/comgle/post/repository/PostRepositoryImpl.java
  src/main/java/com/project/comgle/post/service/LogService.java
  src/main/java/com/project/comgle/post/service/PostService.java
  src/main/java/com/project/comgle/post/service/SearchService.java
Labels: Fix, Refactor

#163 Fix : 게시글 상세조회 시 Respone 항목 추가 (#162)
  src/main/java/com/project/comgle/bookmark/controller/BookMarkController.java
  src/main/java/com/project/comgle/bookmark/repository/BookMarkRepository.java
  src/main/java/com/project/comgle/post/dto/PostResponseDto.java
  src/main/java/com/project/comgle/post/repository/KeywordRepositoryImpl.java
  src/main/java/com/project/comgle/post/service/PostService.java
Labels: Fix

#166 feat : 로그인 한 사용자 정보 조회 기능 (#164)
  src/main/java/com/project/comgle/mypage/controller/MyPageController.java
  src/main/java/com/project/comgle/mypage/service/MyPageService.java
Labels: Feat

#160 Refactor : response message 영문으로 변경 (#157)
  src/main/java/com/project/comgle/admin/controller/AdminController.java
  src/main/java/com/project/comgle/admin/dto/SignupRequestDto.java
  src/main/java/com/project/comgle/admin/service/AdminService.java
  src/main/java/com/project/comgle/admin/service/CategoryService.java
  src/main/java/com/project/comgle/auth/dto/EmailAuthRequestDto.java
  src/main/java/com/project/comgle/auth/dto/FindEmailRequestDto.java
  src/main/java/com/project/comgle/bookmark/repository/BookMarkRepository.java
  src/main/java/com/project/comgle/bookmark/service/BookMarkService.java
  src/main/java/com/project/comgle/company/service/CompanyService.java
  src/main/java/com/project/comgle/member/dto/PasswordRequestDto.java
  src/main/java/com/project/comgle/member/service/MemberService.java
  src/main/java/com/project/comgle/post/entity/WeightEnum.java
  src/main/java/com/project/comgle/post/service/PostService.java
  src/main/java/com/project/comgle/post/service/SseService.java
Labels: Refactor

#168 Feat/167/caching
  src/main/java/com/project/comgle/ComgleApplication.java
  src/main/java/com/project/comgle/admin/controller/AdminController.java
  src/main/java/com/project/comgle/admin/repository/CategoryRepository.java
  src/main/java/com/project/comgle/company/entity/Company.java
  src/main/java/com/project/comgle/global/security/UserDetailsServiceImpl.java
  src/main/java/com/project/comgle/member/controller/MemberController.java
  src/main/java/com/project/comgle/member/dto/PositionRequestDto.java
  src/main/java/com/project/comgle/member/entity/Member.java
  src/main/java/com/project/comgle/member/repository/MemberRepository.java
  src/main/java/com/project/comgle/member/service/MemberService.java
  src/main/java/com/project/comgle/post/controller/PostController.java
  src/main/java/com/project/comgle/post/repository/PostRepositoryImpl.java
Labels: Feat

#170 Refactor : Response 통일 (영문) #169
  src/main/java/com/project/comgle/admin/controller/AdminController.java
  src/main/java/com/project/comgle/admin/dto/CategoryRequestDto.java
  src/main/java/com/project/comgle/admin/dto/SignupRequestDto.java
  src/main/java/com/project/comgle/admin/service/AdminService.java
  src/main/java/com/project/comgle/admin/service/CategoryService.java
  src/main/java/com/project/comgle/auth/dto/EmailAuthRequestDto.java
  src/main/java/com/project/comgle/auth/dto/FindEmailRequestDto.java
  src/main/java/com/project/comgle/auth/service/EmailService.java
  src/main/java/com/project/comgle/bookmark/service/BookMarkService.java
  src/main/java/com/project/comgle/comment/service/CommentService.java
  src/main/java/com/project/comgle/company/service/CompanyService.java
  src/main/java/com/project/comgle/global/exception/ExceptionEnum.java
  src/main/java/com/project/comgle/member/dto/PasswordRequestDto.java
  src/main/java/com/project/comgle/member/service/MemberService.java
  src/main/java/com/project/comgle/post/service/PostService.java
Labels: Refactor

#179 Fix : bookMark, myPage Response 버그 수정 #178
  src/main/java/com/project/comgle/bookmark/repository/BookMarkRepository.java
  src/main/java/com/project/comgle/bookmark/service/BookMarkService.java
  src/main/java/com/project/comgle/mypage/service/MyPageService.java
  src/main/java/com/project/comgle/post/dto/PostResponseDto.java
Labels: Fix

#183 refactor
  src/main/java/com/project/comgle/global/exception/ExceptionEnum.java
Labels: Refactor
