Repository Knock-Og/BE, pull requests merged in 2023-03, with the labels that each got.

#5 Update issue templates
  .github/ISSUE_TEMPLATE/create-issue-template.md
Labels: Enhancement

#8 Update issue templates
  .github/ISSUE_TEMPLATE/create-issue-template.md
Labels: Enhancement

#9 Create PR Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Enhancement

#11 Feat : 회원가입 기능 #10
  src/main/java/com/project/comgle/config/WebSecurityConfig.java
  src/main/java/com/project/comgle/controller/MemberController.java
  src/main/java/com/project/comgle/dto/request/CompanyRequestDto.java
  src/main/java/com/project/comgle/dto/request/LoginRequestDto.java
  src/main/java/com/project/comgle/dto/request/SignupRequestDto.java
  src/main/java/com/project/comgle/dto/response/MessageResponseDto.java
  src/main/java/com/project/comgle/entity/Company.java
  src/main/java/com/project/comgle/entity/Member.java
  src/main/java/com/project/comgle/exception/ErrorResponse.java
  src/main/java/com/project/comgle/jwt/JwtAuthFilter.java
  src/main/java/com/project/comgle/jwt/JwtUtil.java
  src/main/java/com/project/comgle/repository/CompanyRepository.java
  src/main/java/com/project/comgle/repository/MemberRepository.java
  src/main/java/com/project/comgle/security/UserDetailsImpl.java
  src/main/java/com/project/comgle/security/UserDetailsServiceImpl.java
  src/main/java/com/project/comgle/service/MemberService.java
Labels: Feat

#14 Feat : 로그인 기능
  src/main/java/com/project/comgle/controller/MemberController.java
  src/main/java/com/project/comgle/entity/Member.java
  src/main/java/com/project/comgle/service/MemberService.java
Labels: Feat

#17 Feat : 승인요청 계정 전체 리스트 조회 기능 (#15)
  src/main/java/com/project/comgle/controller/AdminController.java
  src/main/java/com/project/comgle/dto/request/SignupRequestDto.java
  src/main/java/com/project/comgle/dto/response/PermissionResponseDto.java
  src/main/java/com/project/comgle/entity/Member.java
  src/main/java/com/project/comgle/repository/MemberRepository.java
  src/main/java/com/project/comgle/service/AdminService.java
Labels: Feat

#20 Feat : 이메일 중복 확인 기능 (#13)
  src/main/java/com/project/comgle/controller/MemberController.java
  src/main/java/com/project/comgle/service/MemberService.java
Labels: Feat, Fix

#23 Feat/16/create post
  src/main/java/com/project/comgle/controller/PostController.java
  src/main/java/com/project/comgle/dto/request/PostRequestDto.java
  src/main/java/com/project/comgle/entity/Category.java
  src/main/java/com/project/comgle/entity/Keyword.java
  src/main/java/com/project/comgle/entity/Post.java
  src/main/java/com/project/comgle/entity/PostCategory.java
  src/main/java/com/project/comgle/repository/CategoryRepository.java
  src/main/java/com/project/comgle/repository/PostCategoryRepository.java
  src/main/java/com/project/comgle/repository/PostRepository.java
  src/main/java/com/project/comgle/service/PostService.java
Labels: Feat

#25 Feat : 미승인 회원 승인 기능 (#18)
  src/main/java/com/project/comgle/controller/AdminController.java
  src/main/java/com/project/comgle/entity/Member.java
  src/main/java/com/project/comgle/service/AdminService.java
Labels: Feat

#26 Feat : 직책 변경 기능 (#19)
  src/main/java/com/project/comgle/controller/AdminController.java
  src/main/java/com/project/comgle/dto/request/PositionRequestDto.java
  src/main/java/com/project/comgle/entity/Member.java
  src/main/java/com/project/comgle/service/AdminService.java
Labels: Feat

#31 Feat : 상세페이지 게시글 삭제 기능
  src/main/java/com/project/comgle/controller/PostController.java
  src/main/java/com/project/comgle/repository/KeywordRepository.java
  src/main/java/com/project/comgle/service/PostService.java
Labels: Feat

#32 Feat : 카테고리 추가 기능 (#27)
  src/main/java/com/project/comgle/controller/CategoryController.java
  src/main/java/com/project/comgle/dto/request/CategoryRequestDto.java
  src/main/java/com/project/comgle/repository/CategoryRepository.java
  src/main/java/com/project/comgle/service/CategoryService.java
Labels: Feat

#36 Fix : 회원 승인 및 미 승인 회원 전체 조회 기능 삭제 #35
  src/main/java/com/project/comgle/controller/AdminController.java
  src/main/java/com/project/comgle/service/AdminService.java
Labels: Fix

#37 Feat : 중복 회원명 체크 #34
  src/main/java/com/project/comgle/controller/CategoryController.java
  src/main/java/com/project/comgle/controller/MemberController.java
  src/main/java/com/project/comgle/dto/request/CategoryRequestDto.java
  src/main/java/com/project/comgle/dto/request/CompanyRequestDto.java
  src/main/java/com/project/comgle/repository/MemberRepository.java
  src/main/java/com/project/comgle/service/MemberService.java
Labels: Feat

#47 Fix : 회원가입 기능 수정 (#33)
  src/main/java/com/project/comgle/config/WebSecurityConfig.java
  src/main/java/com/project/comgle/controller/MemberController.java
  src/main/java/com/project/comgle/dto/request/SignupRequestDto.java
  src/main/java/com/project/comgle/entity/Member.java
  src/main/java/com/project/comgle/repository/MemberRepository.java
  src/main/java/com/project/comgle/service/AdminService.java
  src/main/java/com/project/comgle/service/MemberService.java
Labels: Feat

#44 Feat : 즐겨찾기 폴더 추가, 삭제 기능 (#30)
  src/main/java/com/project/comgle/controller/BookMarkController.java
  src/main/java/com/project/comgle/dto/request/BookMarkFolderRequestDto.java
  src/main/java/com/project/comgle/dto/response/BookMarkFolderResponseDto.java
  src/main/java/com/project/comgle/entity/BookMark.java
  src/main/java/com/project/comgle/entity/BookMarkFolder.java
  src/main/java/com/project/comgle/repository/BookMarkFolderRepository.java
  src/main/java/com/project/comgle/repository/BookMarkRepository.java
  src/main/java/com/project/comgle/service/BookMarkService.java
Labels: Feat

#45 Feat : 즐겨찾기 추가, 취소 기능 (#41)
  src/main/java/com/project/comgle/controller/BookMarkController.java
  src/main/java/com/project/comgle/service/BookMarkService.java
Labels: Feat

#49 Feat : 회원 전체 조회 기능 구현 (#48)
  src/main/java/com/project/comgle/controller/AdminController.java
  src/main/java/com/project/comgle/controller/CategoryController.java
  src/main/java/com/project/comgle/controller/MemberController.java
  src/main/java/com/project/comgle/dto/response/MemberResponseDto.java
  src/main/java/com/project/comgle/repository/MemberRepository.java
  src/main/java/com/project/comgle/service/AdminService.java
  src/main/java/com/project/comgle/service/MemberService.java
Labels: Feat

#50 Feat : 게시글 수정 기능
  src/main/java/com/project/comgle/controller/PostController.java
  src/main/java/com/project/comgle/entity/Member.java
  src/main/java/com/project/comgle/entity/Post.java
  src/main/java/com/project/comgle/entity/PostCategory.java
  src/main/java/com/project/comgle/entity/enumSet/PositionEnum.java
  src/main/java/com/project/comgle/repository/PostCategoryRepository.java
  src/main/java/com/project/comgle/repository/PostRepository.java
  src/main/java/com/project/comgle/service/MemberService.java
  src/main/java/com/project/comgle/service/PostService.java
Labels: Feat

#56 Fix : merge issue #55
  src/main/java/com/project/comgle/dto/response/BookMarkFolderResponseDto.java
  src/main/java/com/project/comgle/entity/Member.java
  src/main/java/com/project/comgle/service/MemberService.java
Labels: Fix

#58 Feat : 카테고리 수정 기능 구현 (#57)
  src/main/java/com/project/comgle/controller/CategoryController.java
  src/main/java/com/project/comgle/entity/Category.java
  src/main/java/com/project/comgle/entity/Member.java
  src/main/java/com/project/comgle/repository/CategoryRepository.java
  src/main/java/com/project/comgle/repository/MemberRepository.java
  src/main/java/com/project/comgle/service/CategoryService.java
  src/main/java/com/project/comgle/service/PostService.java
Labels: Feat

#61 Feat : 즐겨찾기 폴더 수정 기능 (#52)(#51)
  src/main/java/com/project/comgle/controller/BookMarkController.java
  src/main/java/com/project/comgle/entity/BookMarkFolder.java
  src/main/java/com/project/comgle/service/BookMarkService.java
Labels: Feat, Fix, Refactor

#62 Feat : 카테고리 전체 조회 기능 (#60)
  src/main/java/com/project/comgle/controller/CategoryController.java
  src/main/java/com/project/comgle/dto/response/CategoryResponseDto.java
  src/main/java/com/project/comgle/entity/Category.java
  src/main/java/com/project/comgle/repository/CategoryRepository.java
  src/main/java/com/project/comgle/security/UserDetailsImpl.java
  src/main/java/com/project/comgle/security/UserDetailsServiceImpl.java
  src/main/java/com/project/comgle/service/CategoryService.java
Labels: Feat

#65 Fix : 회원 가입 시 이메일 중복 관련 이슈 (#64)
  src/main/java/com/project/comgle/config/WebSecurityConfig.java
  src/main/java/com/project/comgle/controller/AdminController.java
  src/main/java/com/project/comgle/repository/MemberRepository.java
  src/main/java/com/project/comgle/service/AdminService.java
Labels: Fix

#71 Refactor : 즐겨찾기 전체 기능에 바뀐 Api와 요구사항 적용 (#63)
  src/main/java/com/project/comgle/controller/BookMarkController.java
  src/main/java/com/project/comgle/dto/response/BookMarkFolderResponseDto.java
  src/main/java/com/project/comgle/repository/BookMarkFolderRepository.java
  src/main/java/com/project/comgle/service/BookMarkService.java
Labels: Refactor

#68 feat : 댓글등록 구현 #28
  src/main/java/com/project/comgle/controller/CommentController.java
  src/main/java/com/project/comgle/dto/request/CommentRequestDto.java
  src/main/java/com/project/comgle/entity/Category.java
  src/main/java/com/project/comgle/entity/Comment.java
  src/main/java/com/project/comgle/repository/CommentRepository.java
  src/main/java/com/project/comgle/service/CommentService.java
Labels: Feat

#70 Feat : 댓글삭제 구현
  src/main/java/com/project/comgle/controller/CommentController.java
  src/main/java/com/project/comgle/service/CommentService.java
Labels: Feat

#75 Refactor : 댓글삭제 구현코드 리팩토링
  src/main/java/com/project/comgle/entity/Category.java
  src/main/java/com/project/comgle/service/CommentService.java
Labels: Refactor

#76 Feat : 마이페이지 즐겨찾기 폴더 별 조회 기능 (#53)
  src/main/java/com/project/comgle/controller/BookMarkController.java
  src/main/java/com/project/comgle/repository/BookMarkRepository.java
  src/main/java/com/project/comgle/service/BookMarkService.java
Labels: Feat

#81 Fix : PostCategory Entity 삭제 (#80)
  src/main/java/com/project/comgle/controller/BookMarkController.java
  src/main/java/com/project/comgle/entity/Post.java
  src/main/java/com/project/comgle/entity/PostCategory.java
  src/main/java/com/project/comgle/repository/KeywordRepository.java
  src/main/java/com/project/comgle/repository/PostCategoryRepository.java
  src/main/java/com/project/comgle/service/BookMarkService.java
  src/main/java/com/project/comgle/service/CategoryService.java
  src/main/java/com/project/comgle/service/PostService.java
Labels: Fix

#84 feat : 댓글조회 구현 (#78)
  src/main/java/com/project/comgle/controller/CommentController.java
  src/main/java/com/project/comgle/dto/response/CommentResponseDto.java
  src/main/java/com/project/comgle/repository/CommentRepository.java
  src/main/java/com/project/comgle/service/CommentService.java
Labels: Feat

#85 Feat : 메인페이지 키워드 검색 조회 #83
  src/main/java/com/project/comgle/controller/SearchController.java
  src/main/java/com/project/comgle/dto/response/PostResponseDto.java
  src/main/java/com/project/comgle/entity/Keyword.java
  src/main/java/com/project/comgle/repository/CommentRepository.java
  src/main/java/com/project/comgle/repository/KeywordRepository.java
  src/main/java/com/project/comgle/repository/PostRepository.java
  src/main/java/com/project/comgle/service/PostService.java
  src/main/java/com/project/comgle/service/SearchService.java
Labels: Feat, Fix

#87 Feat : 댓글수정 구현
  src/main/java/com/project/comgle/controller/CommentController.java
  src/main/java/com/project/comgle/dto/request/CommentRequestDto.java
  src/main/java/com/project/comgle/entity/Comment.java
  src/main/java/com/project/comgle/service/BookMarkService.java
  src/main/java/com/project/comgle/service/CommentService.java
  src/main/java/com/project/comgle/service/MemberService.java
Labels: Feat

#90 Feat/89/swagger
  src/main/java/com/project/comgle/config/SwaggerConfig.java
  src/main/java/com/project/comgle/config/WebSecurityConfig.java
  src/main/java/com/project/comgle/controller/AdminController.java
  src/main/java/com/project/comgle/controller/BookMarkController.java
  src/main/java/com/project/comgle/controller/CategoryController.java
  src/main/java/com/project/comgle/controller/CommentController.java
  src/main/java/com/project/comgle/controller/MemberController.java
  src/main/java/com/project/comgle/controller/PostController.java
  src/main/java/com/project/comgle/dto/common/SchemaDescriptionUtils.java
  src/main/java/com/project/comgle/dto/request/BookMarkFolderRequestDto.java
  src/main/java/com/project/comgle/dto/request/CategoryRequestDto.java
  src/main/java/com/project/comgle/dto/request/CommentRequestDto.java
  src/main/java/com/project/comgle/dto/request/CompanyRequestDto.java
  src/main/java/com/project/comgle/dto/request/LoginRequestDto.java
  src/main/java/com/project/comgle/dto/request/PositionRequestDto.java
  src/main/java/com/project/comgle/dto/request/PostRequestDto.java
  src/main/java/com/project/comgle/dto/request/SignupRequestDto.java
  src/main/java/com/project/comgle/dto/response/BookMarkFolderResponseDto.java
  src/main/java/com/project/comgle/dto/response/CategoryResponseDto.java
  src/main/java/com/project/comgle/dto/response/CommentResponseDto.java
  src/main/java/com/project/comgle/dto/response/MemberResponseDto.java
  src/main/java/com/project/comgle/dto/response/MessageResponseDto.java
  src/main/java/com/project/comgle/dto/response/PostResponseDto.java
Labels: Feat

#91 Feat : Searched Page 카테고리 검색 조회 기능 #82
  src/main/java/com/project/comgle/controller/PostController.java
  src/main/java/com/project/comgle/controller/SearchController.java
  src/main/java/com/project/comgle/repository/CategoryRepository.java
  src/main/java/com/project/comgle/repository/CommentRepository.java
  src/main/java/com/project/comgle/repository/PostRepository.java
  src/main/java/com/project/comgle/service/SearchService.java
Labels: Feat, Fix

#93 Refactor : 예외처리 (#92)
  src/main/java/com/project/comgle/controller/BookMarkController.java
  src/main/java/com/project/comgle/controller/CategoryController.java
  src/main/java/com/project/comgle/controller/MemberController.java
  src/main/java/com/project/comgle/dto/common/ErrorResponse.java
  src/main/java/com/project/comgle/dto/common/SuccessResponse.java
  src/main/java/com/project/comgle/exception/CustomException.java
  src/main/java/com/project/comgle/exception/ExceptionEnum.java
  src/main/java/com/project/comgle/exception/GlobalExceptionHandler.java
  src/main/java/com/project/comgle/jwt/JwtAuthFilter.java
  src/main/java/com/project/comgle/service/BookMarkService.java
Labels: Refactor

#95 Refactor : CommentService CustomException 적용 (#94)
  src/main/java/com/project/comgle/controller/CommentController.java
  src/main/java/com/project/comgle/service/CommentService.java
Labels: Refactor

#99 Feat : 내 게시글 전체조회 구현 (#96)
  src/main/java/com/project/comgle/controller/MyPageController.java
  src/main/java/com/project/comgle/dto/response/PostResponseDto.java
  src/main/java/com/project/comgle/repository/PostRepository.java
  src/main/java/com/project/comgle/service/MyPageService.java
Labels: Feat

#102 Feat : 중요도 순 검색 결과 정렬 #100
  src/main/java/com/project/comgle/dto/response/PostResponseDto.java
  src/main/java/com/project/comgle/entity/Post.java
  src/main/java/com/project/comgle/entity/WeightEnum.java
  src/main/java/com/project/comgle/repository/BookMarkRepository.java
  src/main/java/com/project/comgle/repository/KeywordRepository.java
  src/main/java/com/project/comgle/repository/PostRepository.java
  src/main/java/com/project/comgle/service/BookMarkService.java
  src/main/java/com/project/comgle/service/CommentService.java
  src/main/java/com/project/comgle/service/PostService.java
  src/main/java/com/project/comgle/service/SearchService.java
Labels: Feat

#103 Feat : 로그1차구현(차선책) (#101)
  src/main/java/com/project/comgle/controller/PostController.java
  src/main/java/com/project/comgle/entity/Log.java
  src/main/java/com/project/comgle/repository/LogRepository.java
  src/main/java/com/project/comgle/service/PostService.java
Labels: Feat

#106 Refactor : 관리자, 카테고리 도메인 예외처리 적용 (#105)
  src/main/java/com/project/comgle/config/WebSecurityConfig.java
  src/main/java/com/project/comgle/controller/AdminController.java
  src/main/java/com/project/comgle/controller/CategoryController.java
  src/main/java/com/project/comgle/controller/MemberController.java
  src/main/java/com/project/comgle/controller/PostController.java
  src/main/java/com/project/comgle/controller/SearchController.java
  src/main/java/com/project/comgle/dto/request/PositionRequestDto.java
  src/main/java/com/project/comgle/entity/Category.java
  src/main/java/com/project/comgle/entity/enumSet/PositionEnum.java
  src/main/java/com/project/comgle/exception/CustomAccessDeniedHandler.java
  src/main/java/com/project/comgle/exception/ExceptionEnum.java
  src/main/java/com/project/comgle/exception/GlobalExceptionHandler.java
  src/main/java/com/project/comgle/security/UserDetailsImpl.java
  src/main/java/com/project/comgle/service/AdminService.java
  src/main/java/com/project/comgle/service/CategoryService.java
  src/main/java/com/project/comgle/service/PostService.java
  src/main/java/com/project/comgle/service/SearchService.java
Labels: Refactor

#108 Fix : 로그1차구현(차선책)_게시글편집일시 수정
  src/main/java/com/project/comgle/entity/Log.java
  src/main/java/com/project/comgle/service/PostService.java
Labels: Fix

#110 Feat : 로그1차(차선책) 조회구현
  src/main/java/com/project/comgle/controller/LogController.java
  src/main/java/com/project/comgle/dto/response/LogResponseDto.java
  src/main/java/com/project/comgle/repository/LogRepository.java
  src/main/java/com/project/comgle/repository/PostRepository.java
  src/main/java/com/project/comgle/service/LogService.java
Labels: Feat

#115 Feat : Naver SMS로 문자인증 구현 (#114)
  src/main/java/com/project/comgle/config/WebSecurityConfig.java
  src/main/java/com/project/comgle/controller/LogController.java
  src/main/java/com/project/comgle/controller/MemberController.java
  src/main/java/com/project/comgle/dto/common/SchemaDescriptionUtils.java
  src/main/java/com/project/comgle/dto/request/FindEmailRequestDto.java
  src/main/java/com/project/comgle/dto/request/SignupRequestDto.java
  src/main/java/com/project/comgle/entity/Member.java
  src/main/java/com/project/comgle/exception/ExceptionEnum.java
  src/main/java/com/project/comgle/repository/MemberRepository.java
  src/main/java/com/project/comgle/scheduler/Scheduler.java
  src/main/java/com/project/comgle/service/AdminService.java
  src/main/java/com/project/comgle/service/MemberService.java
  src/main/java/com/project/comgle/sms/controller/SmsController.java
  src/main/java/com/project/comgle/sms/dto/MessageDto.java
  src/main/java/com/project/comgle/sms/dto/SmsRequestDto.java
  src/main/java/com/project/comgle/sms/dto/SmsResponseDto.java
  src/main/java/com/project/comgle/sms/service/SmsService.java
Labels: Feat

#111 Feat : 편집 상태 구현 (SSE)
  src/main/java/com/project/comgle/controller/SseController.java
  src/main/java/com/project/comgle/dto/common/SchemaDescriptionUtils.java
  src/main/java/com/project/comgle/dto/request/PostRequestDto.java
  src/main/java/com/project/comgle/entity/Post.java
  src/main/java/com/project/comgle/entity/SseEmitters.java
  src/main/java/com/project/comgle/repository/EmitterRepository.java
  src/main/java/com/project/comgle/service/PostService.java
  src/main/java/com/project/comgle/service/SseService.java
Labels: Feat

#116 Feat : 이메일 인증 기능 (#113)
  src/main/java/com/project/comgle/config/RedisConfig.java
  src/main/java/com/project/comgle/config/WebSecurityConfig.java
  src/main/java/com/project/comgle/controller/EmailController.java
  src/main/java/com/project/comgle/dto/request/EmailAuthRequestDto.java
  src/main/java/com/project/comgle/dto/response/EmailAuthResponseDto.java
  src/main/java/com/project/comgle/entity/Member.java
  src/main/java/com/project/comgle/exception/GlobalExceptionHandler.java
  src/main/java/com/project/comgle/service/EmailService.java
  src/main/java/com/project/comgle/service/MemberService.java
  src/main/java/com/project/comgle/service/util/RedisUtil.java
  src/main/resources/templates/mail.html
Labels: Feat

#118 Fix : 조회 Response, sse cors, post 삭제 기능 수정, post url 수정 #117
  src/main/java/com/project/comgle/config/WebSecurityConfig.java
  src/main/java/com/project/comgle/controller/PostController.java
  src/main/java/com/project/comgle/dto/common/SchemaDescriptionUtils.java
  src/main/java/com/project/comgle/dto/response/PostResponseDto.java
  src/main/java/com/project/comgle/dto/response/SearchResponseDto.java
  src/main/java/com/project/comgle/repository/BookMarkRepository.java
  src/main/java/com/project/comgle/repository/CommentRepository.java
  src/main/java/com/project/comgle/repository/LogRepository.java
  src/main/java/com/project/comgle/service/PostService.java
Labels: Fix

#122 Feat : CI / CD 구현 #119
  src/main/java/com/project/comgle/service/PostService.java
Labels: Feat
